[package]
name = "aoc_2023"
version = "0.1.0"
authors = ["PlatinPython <platinpython@protonmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
indoc = "2.0.4"
